### ISSUE TITLE
error in pupil finder.py

### ISSUE THREAD

**Issue by veeresh1456** [bvisch/gaze#1]
Warning (from warnings module):
  File "C:\Users\Veeresh Kumar\Desktop\gaze-master\gaze\PupilFinder.py", line 18
    D1 = ((xx-c[0]) * e**2 - gx * e * n**2) / n**4
RuntimeWarning: invalid value encountered in divide

Warning (from warnings module):
  File "C:\Users\Veeresh Kumar\Desktop\gaze-master\gaze\PupilFinder.py", line 19
    D2 = ((yy-c[1]) * e**2 - gy * e * n**2) / n**4
RuntimeWarning: invalid value encountered in divide

**Comment by veeresh1456** [comment]
pupil are not detected

**Comment by bvisch** [comment]
Hi veeresh1456, this code is not yet complete. I'll continue working on it at some point, but for the moment it's on hold. This commit is working, if I remember correctly: https://github.com/bvisch/gaze/commit/9c53a1ce29c2de272a1fe1916c5b32c4fee3c0b3
